name: Deploy Static Content to Arch Linux Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Test SSH Connection
        run: |
          ssh -vvv usr@96.236.219.156 "echo 'SSH connection successful!'"

      - name: Create Target Directory
        run: |
          ssh -vvv usr@96.236.219.156 "mkdir -p /usr/share/nginx/html"

      - name: Deploy Files to Arch Linux Server
        run: |
          rsync -avz --delete ./ usr@96.236.219.156:/usr/share/nginx/html/
