name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Target Directory
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no usr@96.236.219.156 "mkdir -p /usr/share/nginx/html"

      - name: Sync Files to Server
        run: |
          sshpass -e rsync -avz --delete ./ usr@96.236.219.156:/usr/share/nginx/html/
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
